### ISSUE TITLE
I have error when its say i need to put Detours.dll in the main dll but i dont know what is he meaning how i can add the Detours.dll

### ISSUE THREAD

**Issue by Nakik** [Yoticc/MinecraftESP#3]

**Comment by Yoticc** [comment]
There are 3 ways to get Detours.dll:
1) From .zip in https://www.unknowncheats.me/forum/downloads.php?do=file&id=40224
2) Compile it from my repo https://github.com/Yoticc/Detours 
3) Download from https://github.com/Yoticc/Detours/releases/tag/1.0.0
