### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by semihofc** [Yoticc/MinecraftESP#6]
FPS drops way too much and uses more CPU/GPU then normal whether enabling or not enabling. I mean -300 fps / the point it's gonna stutter just because of an ESP isn't good.
Can you eloborate if it's a bug or?

**Comment by Yoticc** [comment]
Must be:
```
                             /                               Consumption                            
State                        /                               CPU     /     GPU
ESP off                                                      No            Little
ESP off and frame has much things                            No            Low
ESP on                                                       Normal        Low
ESP on and frame has much things                             High          Normal
```

If you have any problems with performance. Write to me on discord — `nativeaot`, I’ll send you dev version of ESP and if there is this problem, we’ll look into it

**Comment by semihofc** [comment]
After DLL injection, fan noise speeds up, i get -300-400 fps no matter ESP is on or not, and it affects so much that i can't even play anymore

**Comment by Yoticc** [comment]
The performance issue was not completely resolved by using the dll from the latest [commit](https://github.com/Yoticc/MinecraftESP/commit/e6925bf89a06d46a106742c94a8a16d59df8c35f). I am don't release due to problems with UC. If anyone needs a personal build, write to discord — `nativeoat`
