### ISSUE TITLE
NaotDefines not found

### ISSUE THREAD

**Issue by EgorovUser** [Yoticc/MinecraftESP#7]
Hello!
When compiling, it says that the NAOT package was not found
NaotDefines too, but I think they are related

The previous build works for me, but the newest one doesn’t :(

**Comment by Yoticc** [comment]
Yes. This is a class from the dev-version of the nuget package "korn". You should use the code from latest release to compile instead of the code from latest commit

**Comment by EgorovUser** [comment]
Unfortunately, the compiled file from the release does not work on my server
File from the TEMP folder from the last commit, works
Can I contact you?

**Comment by Yoticc** [comment]
It's weird.
Contacts:
tg: yotic
ds: nativeaot
